[delta]
  dark = false
  side-by-side = true
  true-color = always
  file-added-label = [+]
  file-copied-label = [==]
  file-modified-label = [M]
  file-removed-label = [-]
  file-renamed-label = [->]
  zero-style = syntax
  syntax-theme = ansi
  hunk-header-decoration-style = omit
  hunk-header-style = line-number syntax bold italic
  line-numbers = true
  line-numbers-left-format = " {nm:>3} "
  line-numbers-right-format = " {np:>3} "
  wrap-max-lines = unlimited
  wrap-right-percent = 1

  minus-style = syntax "#3f2d3d"
  minus-non-emph-style = syntax "#3f2d3d"
  minus-emph-style = syntax "#763842"
  minus-empty-line-marker-style = syntax "#3f2d3d"
  line-numbers-minus-style = "#914c54"
  plus-style = syntax "#283b4d"
  plus-non-emph-style = syntax "#283b4d"
  plus-emph-style = syntax "#316172"
  plus-empty-line-marker-style = syntax "#283b4d"
  line-numbers-plus-style = "#449dab"
  line-numbers-zero-style = "#3b4261"
