[delta]
  # author: https://github.com/ahkohd
  dark = false
  side-by-side = true
  true-color = always
  file-added-label = [+]
  file-copied-label = [==]
  file-modified-label = [M]
  file-removed-label = [-]
  file-renamed-label = [->]
  zero-style = syntax
  syntax-theme = ansi
  hunk-header-decoration-style = omit
  hunk-header-style = line-number syntax bold italic
  line-numbers = true
  line-numbers-left-format = " {nm:>3}"
  line-numbers-right-format = " {np:>3}"
  wrap-max-lines = unlimited
  wrap-right-percent = 1
