[delta]
  # author: https://github.com/sarpuser
  dark = true
  side-by-side = true
  true-color = always
  file-added-label = [+]
  file-copied-label = [==]
  file-modified-label = [M]
  file-removed-label = [-]
  file-renamed-label = [->]
  file-style = "#ff9b00" ul bold
  file-decoration-style = "#ea00ff" box ul
  zero-style = syntax
  syntax-theme = Solarized (dark)
  commit-decoration-style ="#ea00ff" ul
  hunk-header-decoration-style = omit
  hunk-header-file-style = "#ff9b00" ul bold
  hunk-header-line-number-style = "#ffd21a" bold
  hunk-header-style = line-number syntax bold italic
  line-numbers = true
  line-numbers-left-format = "{nm:>1}|"
  line-numbers-left-style = "#ea00ff"
  line-numbers-minus-style = "#ff0051" bold
  line-numbers-plus-style = "#1ac71e" bold
  line-numbers-right-format = "{np:>1}|"
  line-numbers-right-style = "#ea00ff"
  line-numbers-zero-style = "#aaaaaa" italic
  minus-emph-style = syntax bold "#b80000"
  minus-style = syntax "#5d001e"
  plus-emph-style = syntax bold "#1a861a"
  plus-style = syntax "#2a5e37"
  whitespace-error-style = "#280050"
  wrap-max-lines = unlimited
  wrap-right-percent = 1
